repos:

- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.31.1
  hooks:
    - id: markdownlint
      name: markdown linting

- repo: https://github.com/thlorenz/doctoc
  rev: v2.1.0
  hooks:
    - id: doctoc
      name: update toc

- repo: https://github.com/yelp/detect-secrets.git
  rev: v1.2.0
  hooks:
    - id: detect-secrets
      name: detect secrets
      args: ['--baseline', '.secrets.baseline']
      exclude: .*/go.sum

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
    - id: trailing-whitespace
      name: trailing whitespace
    - id: end-of-file-fixer
      name: end of file fixer
    - id: check-added-large-files
      name: check added large files
    - id: check-yaml
      name: check yaml
    - id: check-json
      name: check json

# do not pass files to ansible-lint, see:
# https://github.com/ansible/ansible-lint/issues/611
- repo: https://github.com/ansible/ansible-lint.git
  rev: v6.0.2
  hooks:
    - id: ansible-lint
      name: ansible linting
      entry: ansible-lint --force-color ./ansible
      pass_filenames: false
