---
- name: cloud
  connection: local
  gather_facts: false
  hosts: all
  vars:
    ansible_python_interpreter: '/usr/bin/python3'
  become: true
  tasks:

    - name: gcp
      block:
        - name: add google-cloud-sdk.repo
          ansible.builtin.copy:
            src: ./config/google-cloud-sdk.repo
            dest: /etc/yum.repos.d/google-cloud-sdk.repo
            mode: '0444'
        - name: install gcloud
          ansible.builtin.dnf:
            name: google-cloud-sdk
            state: present
        - name: install gcp components
          ansible.builtin.dnf:
            name: "{{ item }}"
            state: present
          loop:
            - kubectl
      become: true
      become_user: root
