---
- name: cockpit
  connection: local
  hosts: all
  gather_facts: true
  vars:
    ansible_python_interpreter: '/usr/bin/python3'
  become: true
  tasks:

    - name: install cockpit
      yum:
        name: "{{ item }}"
        state: latest
      loop:
        - cockpit
    - name: cockpit service
      systemd:
        state: started
        name: cockpit
        daemon_reload: true
    - name: cockpit.socket service
      systemd:
        name: cockpit.socket
        state: started
        enabled: true
        daemon_reload: true
    - name: firewall service
      systemd:
        state: started
        name: firewalld
        daemon_reload: true
    - name: cockpit firewall
      firewalld:
        service: cockpit
        state: enabled
    - name: cockpit firewall (permanent)
      firewalld:
        service: cockpit
        permanent: true
        state: enabled
