---
- name: docker
  connection: local
  gather_facts: false
  hosts: all
  vars:
    ansible_python_interpreter: '/usr/bin/python3'
  become: true
  tasks:

    - name: docker
      block:
        - name: install docker
          ansible.builtin.yum:
            name:
              - docker
            state: present
        - name: suppress warning
          ansible.builtin.file:
            path: /etc/containers/nodocker
            state: touch
            modification_time: preserve
            access_time: preserve
            mode: '0444'
      become: true
      become_user: root

    - name: pull images
      ansible.builtin.command: docker pull '{{ item }}'
      loop:
        - 'postgres:11.6-alpine'
      become_user: vagrant
