---
- name: git
  connection: local
  gather_facts: false
  hosts: all
  vars:
    ansible_python_interpreter: '/usr/bin/python3'
  become: true
  tasks:

    - name: git
      block:
        - name: install git
          yum:
            name: git
            state: latest
        - name: add gh-cli.repo
          get_url:
            url: https://cli.github.com/packages/rpm/gh-cli.repo
            dest: /etc/yum.repos.d/gh-cli.repo
        - name: install 'gh'
          dnf:
            name: gh
            state: latest
      become: true
      become_user: root
