---
- name: hardening
  connection: local
  hosts: all
  gather_facts: true
  collections:
    - devsec.hardening
  vars:
    ansible_python_interpreter: '/usr/bin/python3'
  become: true
  tasks:

    - name: os hardening
      ansible.builtin.include_role:
        name: os_hardening
