---
- name: hashicorp
  connection: local
  gather_facts: false
  hosts: all
  vars:
    ansible_python_interpreter: '/usr/bin/python3'
  become: true
  tasks:

    - name: hashicorp
      block:
        - name: add hashicorp.repo
          ansible.builtin.get_url:
            url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
            dest: /etc/yum.repos.d/hashicorp.repo
            mode: '0444'
        - name: install hashicorp tools
          ansible.builtin.yum:
            name: "{{ item }}"
            state: present
          loop:
            - boundary
            - consul
            - packer
            - terraform
            - waypoint
