---
- name: languages
  connection: local
  gather_facts: false
  hosts: all
  vars:
    ansible_python_interpreter: '/usr/bin/python3'
  become: true
  tasks:

    - name: languages
      block:
        - name: install packages
          yum:
            name: "{{ item }}"
            state: latest
          loop:
            - go
            - python39
            - scala

    - name: python
      block:
        - name: add python aliases
          blockinfile:
            path: ~/.bash_profile
            marker: '# <--- python {mark} --->'
            marker_begin: start
            marker_end: end
            block: |
              alias python=python3
              alias pip=pip3
        - name: add ~/.pip
          file:
            path: ~/.pip
            state: directory
        - name: add ~/.pip/pip.conf
          copy:
            src: ./config/pip.conf
            dest: ~/.pip/pip.conf
      become_user: vagrant
