---
- name: osquery
  connection: local
  gather_facts: false
  hosts: all
  vars:
    ansible_python_interpreter: '/usr/bin/python3'
  become: true
  tasks:

    - name: osquery
      block:
        - name: add osquery gpg key
          ansible.builtin.get_url:
            url: https://pkg.osquery.io/rpm/GPG
            dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-osquery
            mode: '0444'
        - name: add 'osquery-s3-rpm.repo'
          ansible.builtin.get_url:
            url: https://pkg.osquery.io/rpm/osquery-s3-rpm.repo
            dest: /etc/yum.repos.d/osquery-s3-rpm.repo
            mode: '0444'
        - name: install osquery
          ansible.builtin.yum:
            name: osquery
            state: present
